In [61]:
import numpy as np
a = np.array([0,1,2,3])
print(a)


[0 1 2 3]


In [4]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
L = range(1000)
%timeit [i*2 for i in L]


62.2 µs ± 736 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
a = np.arange(1000) 
%timeit a**2

1.33 µs ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
#Creating Array #1D
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
 len(a)

4

In [12]:
#2D and 3D array
b = np.array([[1,2,3], [3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
len(b) #returns the size of the first dimension 

2

In [23]:
#1D array -> Vector, 2D array -> Matrix, nD array -> Tensor.
c = np.array([[[0,1],
               [2,3]],
               [[4,5],
               [6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
c.ndim

3

In [25]:
c.shape

(2, 2, 2)

In [27]:
b = np.arange(1,10,2) #start, end (exclusive), step
print(b)
b

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [8]:
c = np.linspace(0,1,44) #start, end (Inclusive), number of points
c

array([0.        , 0.02325581, 0.04651163, 0.06976744, 0.09302326,
       0.11627907, 0.13953488, 0.1627907 , 0.18604651, 0.20930233,
       0.23255814, 0.25581395, 0.27906977, 0.30232558, 0.3255814 ,
       0.34883721, 0.37209302, 0.39534884, 0.41860465, 0.44186047,
       0.46511628, 0.48837209, 0.51162791, 0.53488372, 0.55813953,
       0.58139535, 0.60465116, 0.62790698, 0.65116279, 0.6744186 ,
       0.69767442, 0.72093023, 0.74418605, 0.76744186, 0.79069767,
       0.81395349, 0.8372093 , 0.86046512, 0.88372093, 0.90697674,
       0.93023256, 0.95348837, 0.97674419, 1.        ])

In [10]:
#common array
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.eye(3) #return a 2D array with ones on the diagonal and zero else where, #I 3*3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3,2) #3 is the number of rows, 2 is the number of columns and diagonal is 1

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [16]:
a = np.diag([1,2,3,4]) #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
np.diag(a) #extract diagonal elements from the matrix

array([1, 2, 3, 4])

In [19]:
#create array using random
#create an array of the given shape and populate it with random sample
a = np.random.rand(4)
a


array([0.45031928, 0.65010992, 0.0345664 , 0.65581314])

In [20]:
a = np.random.rand(4,3)
a  #uniform random number

array([[0.38680783, 0.22582518, 0.1404327 ],
       [0.89323606, 0.29832575, 0.26990328],
       [0.61760454, 0.81580721, 0.37561425],
       [0.44726697, 0.62652861, 0.18491706]])

In [47]:
a = np.random.randn(4) #return from "standard normal distribution" random numbers
a

array([ 0.1431708 , -0.15534291,  0.33550111, -2.14764293])

In [52]:
#Basic Data types
a = np.arange(100000000)
a.dtype

dtype('int32')

In [55]:
a = np.arange(10, dtype="float64")
a
a.dtype

dtype('float64')

In [56]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [58]:
d = np.array([1+2j, 2+3j])
print(d.dtype)

complex128


In [59]:
b = np.array([True, True, False, True])
print(b.dtype)

bool


In [60]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

In [65]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
print(a[5])

5


In [67]:
a =np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [68]:
print(a[2,2])

3


In [69]:
a[2,1] = 5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [70]:
#Slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a[1:8:2] #[startindex: endindex(exclusive):step]


array([1, 3, 5, 7])

In [73]:
#we can also combine assignment and slicing
a = np.arange(10)
a[5:]= 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [74]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [21]:
#Copies and Views
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [5]:
np.shares_memory(a,b)

True

In [6]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [7]:
a #eventhough we modified b, it updated 'a' because both shares same memory space

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
a = np.arange(10)
c = a[::2].copy() # force a copy
c

array([0, 2, 4, 6, 8])

In [9]:
np.shares_memory(a,c)

False

In [12]:
c[0] = 10
c


array([10,  2,  4,  6,  8])

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Fancy Indexing
a = np.random.randint(0, 20, 15)
a

array([ 0, 16,  9,  5,  0,  0, 12, 15, 13, 12,  6, 11, 13,  1, 18])

In [35]:
mask = (a % 2 == 0)
extract_from_a = mask
extract_from_a

array([ True,  True, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False,  True])

In [36]:
extract_from_a = a[mask]
extract_from_a

array([ 0, 16,  0,  0, 12, 12,  6, 18])

In [37]:
#Indexing with a mask can be very useful to assign n new value to sub array:
a[mask] = -1
a

array([-1, -1,  9,  5, -1, -1, -1, 15, 13, -1, -1, 11, 13,  1, -1])

In [38]:
a[mask] = a[mask]*2
a

array([-2, -2,  9,  5, -2, -2, -2, 15, 13, -2, -2, 11, 13,  1, -2])

In [39]:
#Indexing with an array of Integers
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
#Indexing can be done with an array of integers
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [41]:
#New Values Can be Assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [42]:
#Video 2nd
#Elementwise Operations
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [43]:
a + 1

array([2, 3, 4, 5])

In [32]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
b = np.ones(4) +1
b

array([2., 2., 2., 2.])

In [35]:
a - b

array([-1.,  0.,  1.,  2.])

In [45]:
a * b

array([2., 4., 6., 8.])

In [46]:
#Matrix Multiplication
c = np.diag([1,2,3,4])
print(c*c)
print("*********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [42]:
# Elements wise Comparisions
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [43]:
a > b

array([False, False,  True, False])

In [47]:
#Array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)



False

In [48]:
np.array_equal(a,c)

True

In [49]:
#Logical Operations
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [50]:
np.logical_and(a,b)

array([ True, False, False, False])

In [51]:
np.logical_xor(a,b)

array([False,  True,  True, False])

In [55]:
#Transcendental functions
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [58]:
np.log(a) 

C:\Users\Faraz Ahmad\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
np.exp(a) # evaluate e^x for each element

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [60]:
np.sum(a)

10

In [61]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [62]:
x.sum(axis=0) #column (first dimension)

array([3, 3])

In [63]:
x.sum(axis = 1) #row (second dimension)

array([2, 4])

In [64]:
x.min()

1

In [65]:
x.max()

2

In [70]:
x.mean()

1.5

In [71]:
x.mean(axis=0)

array([1.5, 1.5])

In [72]:
x.mean(axis=1)

array([1., 2.])

In [77]:
x = np.random.randint(0, 20, 15)
x

array([ 6,  9, 15, 15, 17, 12, 18, 11, 17, 18, 12,  5, 18,  8,  7])

In [78]:
x.argmin() #address of minimum number

11

In [79]:
x.argmax() #address of maximum number

6

In [80]:
a = np.zeros((50,50)) # creating 50*50 matrix of zeros
np.any(a!=0)  #checking any value of a != 0

False

In [81]:
np.all(a==a) # every value in the matrix are equal

True

In [83]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

In [84]:
np.median(a)

2.0

In [86]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [87]:
np.median(x)

1.5

In [88]:
np.median(y, axis = -1) #last axis(row), axis= 0 is column, axis = 1 is rows

array([2., 5.])

In [91]:
x.std() #ful population standard dev

0.82915619758885

In [63]:
data = np.loadtxt("C:/Users/Faraz Ahmad/Desktop/python_dataset_1.txt")

In [64]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 36200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 76600., 51100., 39000.],
       [ 1916., 52300., 29700., 36700.],
       [ 1917., 19500., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [67]:
year, hare, lynx, carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [68]:
populations = data[:, 1:] # take all the rows, but from 1st column onwards
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 36200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [76600., 51100., 39000.],
       [52300., 29700., 36700.],
       [19500., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [71]:
data.std(axis=0)

array([6.05530071e+00, 2.12792746e+04, 1.62999645e+04, 3.32250623e+03])

In [73]:
np.argmax(data, axis=1)

array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 3, 3, 3, 3],
      dtype=int64)

In [74]:
#Broadcasting: Basic operations on numpy array(addition, etc.) are element wise
# This works on arrays of the same size. Nevertheless, it's also possible to do operations
#on array of different size if NumPy can transform array so that they have the same size: this
#concversion is called broadcasting.


In [75]:
a  = np.tile(np.arange(0,40,10), (3,1))
print(a)

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [76]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [77]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [81]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [84]:
a = a[:, np.newaxis] #add a new axis -> 2D array
a.shape

(4, 1)

In [85]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [86]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [87]:
#Flattening
a = np.array([[1,2,3], [4,5,6]]) # 2D array
a.ravel() #return a contigous flattened array, Converts 2D to 1-D array


array([1, 2, 3, 4, 5, 6])

In [88]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [90]:
print(a.shape)
print(a)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [91]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [92]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [100]:
#Note and Beware: reshape may also return a copy!:
a = np.zeros((3,2))
b = a.T.reshape(3,2)
b[0,0] = 50
b
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
b

array([[50.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [102]:
a= np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [103]:
a = np.arange(4*3*2).reshape(4,3,2)  # 4 matrix of 3*2 sizes
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [104]:
a[0,2,1]

5

In [106]:
#Resizing
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [107]:
b = a
a.resize((4,)) #cannot resize an array that references or is referenced
#by another array in this way.

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [108]:
#sorting along the axis
a = np.array([[5,4,6], [2,3,2]])
b = np.sort(a, axis =1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [110]:
#sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a)
j
  

array([2, 3, 1, 0], dtype=int64)

In [111]:
a[j]

array([1, 2, 3, 4])